### ISSUE TITLE
⚡️Features Roadmap

### ISSUE THREAD

**Issue by hazadus** [hazadus/next-bredit#6]
## Features I want to build in this project

- [x] #7
- [x] Add Sentry to project
- Navbar
    - [x] More items in user menu
    - [x] Add tooltips to buttons
    - [ ] Search dropdown
- Home page
    - [ ] "Recent posts" component
    - [ ] Infinite scroll
- User
    - [ ] Profile page
        - [ ] #13
        - [ ] Public profile – Comments tab
        - [ ] Public profile – Overview tab
        - [ ] Upload profile picture
        - [ ] User karma
        - [ ] Show all user's posts in profile
        - [ ] Show all user's comments in profile
- Community
    - [ ] Edit community description
- Popular posts
- Posts 
    - [x] Tooltip with full date/time (https://chakra-ui.com/docs/components/tooltip/usage#with-arrow )
    - [ ] Tune SEO (SSR meta info)
    - [ ] Share menu (copy to clipboard, toast https://chakra-ui.com/docs/components/toast/usage#variants )
    - [ ] Edit post
    - [x] #9
    - [ ] Auto-resize post body textarea
    - [ ] Blur long posts
- Comments   
    - [x] #11
    - [x] Tooltip with full date/time (https://chakra-ui.com/docs/components/tooltip/usage#with-arrow )
    - [ ] Nested comments
    - [ ] Edit comment
    - [ ] Vote on comments
- Notifications
    - [ ] Comment for user's post

**Comment by hazadus** [comment]
Add some tests https://youtu.be/XTNqyEBPAFw?si=kpszn4tSw13JNYkC

**Comment by hazadus** [comment]
Ordering https://firebase.google.com/docs/firestore/query-data/order-limit-data?hl=en#order_and_limit_data

Pagination https://firebase.google.com/docs/firestore/query-data/query-cursors

Count results https://firebase.google.com/docs/firestore/query-data/aggregation-queries?hl=en#use_the_count_aggregation
